export const vehicleBrands : VehicleBrands[] = [
    { name: 'Alfa Romeo', models: ['Stelvio', 'Spider', 'Giulia'] },
    { name: 'Audi', models: ['A3', 'A6', 'Q3'] },
    { name: 'BMW', models: ['3 Series','5 Series','M3'] },
    { name: 'Chevrolet', models: ['Camaro', 'Tahoe', 'Malibu'] },
    { name: 'Chrysler', models: ['300', 'Voyager', 'Pacifica'] },
    { name: 'Citroën', models: ['C3','C5','Cactus'] },
    { name: 'Fiat', models: ['500X','Spider','500L'] },
    { name: 'Ford', models:['F-150','Mustang','Ranger'] },
    { name: 'Holden', models:['Apollo','Astra','Berlina'] },
    { name: 'Honda', models: ['Civic','Accord','Insight'] },
    { name: 'Hyundai', models: ['Tucson','Accent','Santa Fe'] },
    { name: 'Infiniti', models:['Q50','Q60','QX60'] },
    { name: 'Isuzu', models: ['Ascender','Trooper','Amigo'] },
    { name: 'Iveco', models: ['Trakker','Stralis','Strator'] },
    { name: 'Jaguar', models: ['F-TYPE','F-PACE','XF'] },
    { name: 'Jeep', models: ['Wrangler','Compass','Wagoneer'] },
    { name: 'Kia', models: ['Rio','Optima','Seltos'] },
    { name: 'Land Rover', models: ['Defender','Range Rover','Rover Sport'] },
    { name: 'Lexus', models: ['RX','NX','IS'] },
    { name: 'MAN', models: ['CLA','TGM','TGA'] },
    { name: 'Mazda', models: ['CX-5','Mazda 3','Mazda CX-3'] },
    { name: 'Mercedes-Benz', models: ['A-Class','C-Class','S-Class'] },
    { name: 'Mini', models: ['Cooper','Countryman','Clubman'] },
    { name: 'Mitsubishi', models: ['Outlander','mirage','Eclipse Cross'] },
    { name: 'Nissan', models: ['Versa','GT-R','Frontier'] },
    { name: 'Opel', models: ['Astra','Corsa','Cascada'] },
    { name: 'Peugeot', models: ['Boxer','208','Traveller'] },
    { name: 'Porsche', models: ['911','Cayenne','Taycan'] },
    { name: 'Renault', models:['Kiger','KWID','Triber'] },
    { name: 'Saab', models: ['Quantum','MFI13','900'] },
    { name: 'Scania', models: ['L-Series','P-Series','R-Series'] },
    { name: 'Seat', models: ['Arona','Tarraco','Leon'] },
    { name: 'Skoda', models: ['Octavia','Superb','New Rapid'] },
    { name: 'smart', models: ['fortwo','forfour','Roadster'] },
    { name: 'Subaru', models: ['Forester','Crosstrek','WRX'] },
    { name: 'Suzuki', models: ['Swift','SX4','Grand Vitara'] },
    { name: 'Tesla', models: ['Model 3','Model X','Model Y'] },
    { name: 'Toyota', models: ['RAV4','Corolla','Camry'] },
    { name: 'Volkswagen', models: ['Golf','Passat','Jetta'] },
    { name: 'Volvo', models: ['XC60','XC40','V90'] }
];
