export const vehicleBrands : VehicleBrands[] = [
    { brand: 'Alfa Romeo', models: ['Stelvio', 'Spider', 'Giulia'], vinBase: 'ZARBAAC40EM' },
    { brand: 'Audi', models: ['A3', 'A6', 'Q3'], vinBase: 'WA1WGCFE0C0' },
    { brand: 'BMW', models: ['3 Series', '5 Series', 'M3'], vinBase: 'WBAKF9C52BE' },
    { brand: 'Chevrolet', models: ['Camaro', 'Tahoe', 'Malibu'], vinBase: '3GNCJKSB2EL' },
    { brand: 'Chrysler', models: ['300', 'Voyager', 'Pacifica'], vinBase: '2C3CCADT4EH' },
    { brand: 'Citroën', models: ['C3', 'C5', 'Cactus'], vinBase: 'VF72RHNPXK4' },
    { brand: 'Fiat', models: ['500X', 'Spider', '500L'], vinBase: '3C3BFFER5DT' },
    { brand: 'Ford', models: ['F-150', 'Mustang', 'Ranger'], vinBase: '1FTFX1CF9DK' },
    { brand: 'Holden', models: ['Apollo', 'Astra', 'Berlina'], vinBase: '80737KH5143' },
    { brand: 'Honda', models: ['Civic', 'Accord', 'Insight'], vinBase: '5J6TF3H37DL' },
    { brand: 'Hyundai', models: ['Tucson', 'Accent', 'Santa Fe'], vinBase: 'KM8JUCAGXEU' },
    { brand: 'Infiniti', models: ['Q50', 'Q60', 'QX60'], vinBase: 'JN1CV6FP0A0' },
    { brand: 'Isuzu', models: ['Ascender', 'Trooper', 'Amigo'], vinBase: '4NUDS13S762' },
    { brand: 'Iveco', models: ['Trakker', 'Stralis', 'Strator'], vinBase: '4NUDS13S762' },
    { brand: 'Jaguar', models: ['F-TYPE', 'F-PACE', 'XF'], vinBase: 'SAJWA0HP2DM' },
    { brand: 'Jeep', models: ['Wrangler', 'Compass', 'Wagoneer'], vinBase: '1C4PJMCB1FW' },
    { brand: 'Kia', models: ['Rio', 'Optima', 'Seltos'], vinBase: 'KNDPC3A25B7' },
    { brand: 'Land Rover', models: ['Defender', 'Range Rover', 'Rover Sport'], vinBase: 'SALVT1BG9EH' },
    { brand: 'Lexus', models: ['RX', 'NX', 'IS'], vinBase: 'JTHDL5EF1E5' },
    { brand: 'MAN', models: ['CLA', 'TGM', 'TGA'], vinBase: 'WMAN48ZZ07Y' },
    { brand: 'Mazda', models: ['CX-5', 'Mazda 3', 'Mazda CX-3'], vinBase: 'JM1BL1VG0C1' },
    { brand: 'Mercedes-Benz', models: ['A-Class', 'C-Class', 'S-Class'], vinBase: 'WDDGF4HB8CR' },
    { brand: 'Mini', models: ['Cooper', 'Countryman', 'Clubman'], vinBase: 'WMWSX1C57DT' },
    { brand: 'Mitsubishi', models: ['Outlander', 'mirage', 'Eclipse Cross'], vinBase: 'JA4AZ4AX7EZ' },
    { brand: 'Nissan', models: ['Versa', 'GT-R', 'Frontier'], vinBase: 'JN6BE6DS5E9' },
    { brand: 'Opel', models: ['Astra', 'Corsa', 'Cascada'], vinBase: 'WOLOXCFO14O' },
    { brand: 'Peugeot', models: ['Boxer', '208', 'Traveller'], vinBase: 'VF3CF2210M0' },
    { brand: 'Porsche', models: ['911', 'Cayenne', 'Taycan'], vinBase: 'WP0AB29828U' },
    { brand: 'Renault', models: ['Kiger', 'KWID', 'Triber'], vinBase: 'VF1AA22B2G3' },
    { brand: 'Saab', models: ['Quantum', 'MFI13', '900'], vinBase: 'YS3FB4CY9B1' },
    { brand: 'Scania', models: ['L-Series', 'P-Series', 'R-Series'], vinBase: 'YS2k4X20001' },
    { brand: 'Seat', models: ['Arona', 'Tarraco', 'Leon'], vinBase: 'VSSZZZ5FZLR' },
    { brand: 'Skoda', models: ['Octavia', 'Superb', 'New Rapid'], vinBase: 'TMBJS21Z998' },
    { brand: 'smart', models: ['fortwo', 'forfour', 'Roadster'], vinBase: 'WMEEJ3BA0EK' },
    { brand: 'Subaru', models: ['Forester', 'Crosstrek', 'WRX'], vinBase: '4S4BRBHC6B1' },
    { brand: 'Suzuki', models: ['Swift', 'SX4', 'Grand Vitara'], vinBase: 'JS1NP41A4E2' },
    { brand: 'Tesla', models: ['Model 3', 'Model X', 'Model Y'], vinBase: '5YJSA1S1XFF' },
    { brand: 'Toyota', models: ['RAV4', 'Corolla', 'Camry'], vinBase: 'JTDKN3DU2F2' },
    { brand: 'Volkswagen', models: ['Golf', 'Passat', 'Jetta'], vinBase: '3VW817AU6FD' },
    { brand: 'Volvo', models: ['XC60', 'XC40', 'V90'], vinBase: 'YV1MK84F1D2' }
];
