name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    permissions:
        contents: read
        id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build and test
        run: pnpm build && pnpm test && pnpm lint

      - name: Publish to npm
        run: npm publish --provenance --access public
